_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 12
                - 55
            "2":
                - 1
                - 12
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
NKL:
    value: 50
chunks:
    value: 16
decay_rate:
    value: 0.9
dim_initial_condition:
    value: 128
iterations:
    value: 2000
learning_rate:
    value: 0.001
model:
    value: MDNN
points_per_chunk:
    value: 250
samples_size_initial:
    value: 10
scheduler_step_epochs:
    value: 250
seed:
    value: 108
time_domain:
    value: 2
weights_update:
    value: 500
