beta_end: 0.2
beta_fn: linear
beta_start: 0.0001
continuous_t1: 1
data_mean: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADE2Njg0MjI0MHECWAMAAABjcHVxA0sDTnRxBFEugAJdcQBYCQAAADE2Njg0MjI0
    MHEBYS4DAAAAAAAAAOA32D34Z1s819yuPg==
- 0
- !!python/tuple
  - 3
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
data_std: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADE2NjY0MDkxMnECWAMAAABjcHVxA0sDTnRxBFEugAJdcQBYCQAAADE2NjY0MDkx
    MnEBYS4DAAAAAAAAAEXC5T8LwwlAOJ1qPw==
- 0
- !!python/tuple
  - 3
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
diffusion: GPDiffusion
dim: 3
discrete_num_steps: 100
gp_sigma: 0.1
hidden_dim: 128
learning_rate: 0.001
loss_weighting: exponential
max_t: 1.0
model: rnn
ou_theta: 0.5
predict_gaussian_noise: true
weight_decay: 0
